const ENCODE = 'encode';
const DECODE = 'decode';
const ALPHABET_LENGTH = 26;
const LOWERCASE_START_CODE = 65;
const LOWERCASE_END_CODE = LOWERCASE_START_CODE + ALPHABET_LENGTH - 1;
const UPPERCASE_START_CODE = 97;
const UPPERCASE_END_CODE = UPPERCASE_START_CODE + ALPHABET_LENGTH - 1;

module.exports = {
  ENCODE,
  DECODE,
  ALPHABET_LENGTH,
  LOWERCASE_START_CODE,
  LOWERCASE_END_CODE,
  UPPERCASE_START_CODE,
  UPPERCASE_END_CODE
};
